name: Build Kali NetHunter Kernel for SM-X115

on:
  workflow_dispatch:

jobs:
  build:
    name: Compile Kernel & Create Flashable Magisk ZIP
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clone Kernel Source
      uses: actions/checkout@v4
      with:
        repository: Anmol6002/kernel_source_sm-x115
        ref: main
        path: kernel

    - name: 🧰 Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex libssl-dev libncurses5-dev \
          libelf-dev build-essential git wget cpio rsync zip unzip python3

    - name: 🔧 Clone AOSP GCC Toolchain
      run: |
        git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android \
          -b android10-release toolchain64
        echo "CROSS_COMPILE=$(pwd)/toolchain64/bin/aarch64-linux-android-" >> $GITHUB_ENV

    - name: 🩹 Patch defconfig with NetHunter Configs
      working-directory: kernel
      run: |
        DEFCONFIG="arch/arm64/configs/gta9_defconfig"
        echo -e "\n# --- NetHunter Config Patches ---" >> $DEFCONFIG
        cat << EOF >> $DEFCONFIG 
# Architecture  
CONFIG_ARM64=y
 
# Modules
CONFIG_MODULES=y
CONFIG_MODULE_UNLOAD=y

# ZRAM / Swap / RAM Plus
CONFIG_SWAP=y
CONFIG_ZSMALLOC=y
CONFIG_ZRAM=y
CONFIG_ZRAM_MEMORY_TRACKING=y
CONFIG_CGROUPS=y
CONFIG_MEMCG=y
CONFIG_CGROUP_SCHED=y
CONFIG_FAIR_GROUP_SCHED=y
CONFIG_KSM=y
CONFIG_TRANSPARENT_HUGEPAGE=y

# Android IPC
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
CONFIG_ASHMEM=y

# USB Gadget & OTG
CONFIG_USB_GADGET=y
CONFIG_USB_OTG=y
CONFIG_USB_OTG_FSM=y
CONFIG_USB_GADGET_VBUS_DRAW=500
CONFIG_USB_GADGET_STORAGE_NUM_BUFFERS=2
CONFIG_USB_LIBCOMPOSITE=y
CONFIG_USB_U_SERIAL=y
CONFIG_USB_STORAGE=y
CONFIG_USB_CONFIGFS=y
CONFIG_USB_CONFIGFS_SERIAL=y
CONFIG_USB_CONFIGFS_ACM=y
CONFIG_USB_CONFIGFS_OBEX=y
CONFIG_USB_CONFIGFS_NCM=y
CONFIG_USB_CONFIGFS_ECM=y
CONFIG_USB_CONFIGFS_ECM_SUBSET=y
CONFIG_USB_CONFIGFS_EEM=y
CONFIG_USB_CONFIGFS_RNDIS=y
CONFIG_USB_CONFIGFS_MASS_STORAGE=y
CONFIG_USB_CONFIGFS_F_FS=y
CONFIG_USB_CONFIGFS_F_HID=y
CONFIG_USB_CONFIGFS_F_UAC1=y
CONFIG_USB_CONFIGFS_F_UAC2=y
CONFIG_USB_CONFIGFS_F_MIDI=y
CONFIG_USB_CONFIGFS_F_PRINTER=y
CONFIG_USB_CONFIGFS_F_LB_SS=y
CONFIG_USB_F_FS=y
CONFIG_USB_F_HID=y
CONFIG_USB_F_RNDIS=y
CONFIG_USB_F_ECM=y
CONFIG_USB_F_ACM=y
CONFIG_USB_F_UAC1=y
CONFIG_USB_F_UAC2=y
CONFIG_USB_F_MIDI=y
CONFIG_USB_F_PRINTER=y
CONFIG_USB_F_MASS_STORAGE=y
CONFIG_USB_F_SS_LB=y

# USB Networking
CONFIG_USB_NET_RNDIS_HOST=y
CONFIG_USB_NET_CDCETHER=y
CONFIG_USB_NET_CDC_EEM=y
CONFIG_USB_USBNET=y
CONFIG_USB_RTL8152=y

# USB Serial
CONFIG_USB_SERIAL=y
CONFIG_USB_SERIAL_GENERIC=y
CONFIG_USB_SERIAL_CP210X=y
CONFIG_USB_SERIAL_FTDI_SIO=y
CONFIG_USB_SERIAL_PL2303=y

# Wi-Fi
CONFIG_WIRELESS=y
CONFIG_CFG80211=y
CONFIG_CFG80211_WEXT=y
CONFIG_MAC80211=y

# Realtek Wi-Fi
CONFIG_WLAN_VENDOR_REALTEK=y
CONFIG_RTL8187=y
CONFIG_RTL8188EU=y
CONFIG_RTL8192CU=y
CONFIG_RTLWIFI=y
CONFIG_RTLWIFI_USB=y
CONFIG_RTL8192EU=y
CONFIG_RTL8821AU=m

# Atheros Wi-Fi
CONFIG_WLAN_VENDOR_ATH=y
CONFIG_ATH9K_HTC=y
CONFIG_ATH9K_COMMON=y
CONFIG_CARL9170=y
CONFIG_ATH6KL=y
CONFIG_ATH6KL_USB=y

# MediaTek / Ralink Wi-Fi
CONFIG_WLAN_VENDOR_MEDIATEK=y
CONFIG_MT7601U=y
CONFIG_WLAN_VENDOR_RALINK=y
CONFIG_RT2X00=y
CONFIG_RT2X00_LIB_USB=y
CONFIG_RT2X00_LIB=y
CONFIG_RT2X00_LIB_FIRMWARE=y
CONFIG_RT2500USB=y
CONFIG_RT73USB=y
CONFIG_RT2800USB=y
CONFIG_RT2800USB_RT33XX=y
CONFIG_RT2800USB_RT35XX=y
CONFIG_RT2800USB_RT3573=y
CONFIG_RT2800USB_RT53XX=y

# Netfilter / Networking
CONFIG_PACKET=y
CONFIG_UNIX=y
CONFIG_INET=y
CONFIG_NETFILTER=y
CONFIG_NETFILTER_ADVANCED=y
CONFIG_NF_CONNTRACK=y
CONFIG_NF_CONNTRACK_IPV4=y
CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y
CONFIG_NETFILTER_XT_MATCH_STATE=y
CONFIG_IP_NF_IPTABLES=y
CONFIG_IP_NF_FILTER=y
CONFIG_IP_NF_TARGET_REJECT=y
CONFIG_IP_NF_MANGLE=y
CONFIG_NETFILTER_XT_MATCH_MAC=y
CONFIG_NETFILTER_XT_MATCH_MULTIPORT=y
CONFIG_NETFILTER_XT_MATCH_TCPMSS=y
CONFIG_NETFILTER_XT_MATCH_COMMENT=y
CONFIG_NETFILTER_XT_MATCH_LENGTH=y
CONFIG_IP_ADVANCED_ROUTER=y
CONFIG_IP_MULTICAST=y
CONFIG_IP_PNP=y

# Namespaces
CONFIG_NAMESPACES=y
CONFIG_UTS_NS=y
CONFIG_USER_NS=y
CONFIG_PID_NS=y
CONFIG_NET_NS=y
CONFIG_IPC_NS=y

# Cgroups / Containers
CONFIG_CGROUP_DEVICE=y
CONFIG_CGROUP_FREEZER=y
CONFIG_CGROUP_CPUACCT=y
CONFIG_CPUSETS=y
CONFIG_KEYS=y
CONFIG_USERFAULTFD=y

# File Systems
CONFIG_OVERLAY_FS=y
CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_XZ=y
CONFIG_SQUASHFS_LZ4=y
CONFIG_SQUASHFS_ZSTD=y
CONFIG_SQUASHFS_LZO=y
CONFIG_EXT4_FS=y
CONFIG_TMPFS=y
CONFIG_DEVTMPFS=y
CONFIG_DEVTMPFS_MOUNT=y
CONFIG_BLK_DEV_LOOP=y
CONFIG_F2FS_FS=y
CONFIG_BTRFS_FS=y
CONFIG_VFAT_FS=y
CONFIG_EXFAT_FS=y
CONFIG_NTFS_FS=y
CONFIG_FUSE_FS=y
CONFIG_MSDOS_FS=y

# NFS
CONFIG_NETWORK_FILESYSTEMS=y
CONFIG_NFS_V2=y
CONFIG_NFS_V3=y
CONFIG_NFS_V4=y
CONFIG_NFSD=y
CONFIG_NFSD_V3=y
CONFIG_NFSD_V4=y

# CAN
CONFIG_CAN=y
CONFIG_CAN_RAW=y
CONFIG_CAN_BCM=y
CONFIG_CAN_GW=y
CONFIG_CAN_DEV=y
CONFIG_CAN_CALC_BITTIMING=y
CONFIG_CAN_LEDS=y
CONFIG_CAN_VCAN=y
CONFIG_CAN_SLCAN=m
CONFIG_CAN_PEAK_USB=y
CONFIG_CAN_KVASER_USB=y
CONFIG_CAN_GS_USB=y
CONFIG_CAN_8DEV_USB=y
CONFIG_CAN_EMS_USB=y
CONFIG_CAN_ESD_USB2=y
CONFIG_CAN_CAN327=m
CONFIG_NET_SCH_CANID=y

# SDR
CONFIG_MEDIA_DIGITAL_TV_SUPPORT=y
CONFIG_MEDIA_SDR_SUPPORT=y
CONFIG_MEDIA_USB_SUPPORT=y
CONFIG_USB_AIRSPY=y
CONFIG_USB_HACKRF=y
CONFIG_USB_MSI2500=y
CONFIG_DVB_RTL2830=y
CONFIG_DVB_RTL2832=y
CONFIG_DVB_RTL2832_SDR=y
CONFIG_DVB_SI2168=y
CONFIG_DVB_ZD1301_DEMOD=y
CONFIG_MEDIA_SUBDRV_AUTOSELECT=n

# HID / Input Injection
CONFIG_INPUT=y
CONFIG_INPUT_MISC=y
CONFIG_INPUT_UINPUT=y
CONFIG_HID=y
CONFIG_HID_GENERIC=y
CONFIG_HIDRAW=y
CONFIG_HID_GFRM=y
CONFIG_HID_A4TECH=y
CONFIG_HID_APPLE=y
CONFIG_HID_BELKIN=y
CONFIG_HID_CHERRY=y
CONFIG_HID_CHICONY=y
CONFIG_HID_PRODIKEYS=y
CONFIG_HID_LOGITECH=y
CONFIG_HID_MICROSOFT=y
CONFIG_HID_MULTITOUCH=y
CONFIG_HID_SONY=y

# Debug
CONFIG_DEBUG_FS=y
CONFIG_DEBUG_INFO=y
CONFIG_COREDUMP=y
CONFIG_KALLSYMS=y
CONFIG_DEBUG_KERNEL=y
CONFIG_KPROBES=y
CONFIG_UPROBES=y
CONFIG_KGDB=y
CONFIG_PROC_KCORE=y
CONFIG_MAGIC_SYSRQ=y
CONFIG_PRINTK_TIME=y
CONFIG_LOG_BUF_SHIFT=18

# Power
CONFIG_POWER_SUPPLY=y
CONFIG_POWER_RESET=y
CONFIG_LEDS_CLASS=y

# Touchscreen & Display
CONFIG_INPUT_TOUCHSCREEN=y
CONFIG_TOUCHSCREEN_MTK_FOCALTECH=y
CONFIG_TOUCHSCREEN_MTK_GT9XX=y
CONFIG_DRM=y
CONFIG_DRM_MALI_DISPLAY=y
CONFIG_FB=y
CONFIG_FRAMEBUFFER_CONSOLE=y
CONFIG_FB_SIMPLE=y

# Sound
CONFIG_SND=y
CONFIG_SND_SOC=y
CONFIG_SND_SOC_MTK_BTCVSD=y
CONFIG_SND_SOC_MTK_COMMON=y

# Security
CONFIG_SECURITY_SELINUX=y
CONFIG_SECURITY_SELINUX_BOOTPARAM=y
CONFIG_SECURITY_SELINUX_DISABLE=y
CONFIG_SECCOMP=y
CONFIG_ANDROID_PARANOID_NETWORK=n

# MediaTek Extras
CONFIG_MTK_LEGACY=y
CONFIG_MTK_PLATFORM=y
CONFIG_MTK_INFRACFG=y
CONFIG_MTK_CLKBUF=y
CONFIG_MTK_SCHED=y
CONFIG_MTK_MTK_STATIC_POWER=y
CONFIG_MTK_DEVINFO=y
CONFIG_MTK_EFUSE=y
CONFIG_MTK_THERMAL=y
CONFIG_MTK_CMDQ=y

# GPU
CONFIG_MALI_MIDGARD=m
CONFIG_MALI_DEVFREQ=y
EOF

    - name: 🧪 Compile Kernel & Modules
      working-directory: kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=${{ env.CROSS_COMPILE }}

        make gta9_defconfig
        make -j$(nproc)
        make modules -j$(nproc)

        mkdir -p ../out/modules_install
        make INSTALL_MOD_PATH=../out/modules_install modules_install

    - name: 📦 Pack modules.tar.gz
      run: |
        cd out/modules_install
        tar -czf ../../modules.tar.gz lib

    - name: 🧰 Clone AnyKernel3 & Setup
      run: |
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3 anykernel
        cp kernel/arch/arm64/boot/Image.gz anykernel/

        if [ -d kernel/arch/arm64/boot/dts ]; then
          find kernel/arch/arm64/boot/dts -name "*.dtb" -exec cat {} + > anykernel/dtb
          cat anykernel/Image.gz anykernel/dtb > anykernel/Image.gz-dtb
        else
          cp anykernel/Image.gz anykernel/Image.gz-dtb
        fi

        mkdir -p anykernel/lib/modules
        tar -xzf modules.tar.gz -C anykernel/

        sed -i 's/is_slot_device=0/is_slot_device=1/' anykernel/anykernel.sh
        sed -i 's@kernel_string=.*@kernel_string="NetHunter Kernel for SM-X115"@' anykernel/anykernel.sh

    - name: 📦 Create Magisk Flashable ZIP
      run: |
        cd anykernel
        zip -r9 ../NetHunter-Kernel-SMX115.zip ./*

    - name: 📤 Upload ZIP
      uses: actions/upload-artifact@v3
      with:
        name: NetHunter-Kernel-SMX115
        path: NetHunter-Kernel-SMX115.zip
