name: Build NetHunter Kernel for SM-X115 (LXC + Input)

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    env:
      DEVICE_CODENAME: gta9
      DEFCONFIG: gta9_defconfig
      KERNEL_SOURCES_ZIP: SM-X115_SWA_14_Opensource.zip

    steps:
    - name: Checkout project code
      uses: actions/checkout@v4

    - name: Download kernel source ZIP from Release
      run: |
        wget \
          https://github.com/Anmol6002/nethunter-kernel-smx115/releases/download/SM.x115/${KERNEL_SOURCES_ZIP}

    - name: Extract kernel source
      run: |
        unzip -q ${KERNEL_SOURCES_ZIP} -d kernel_src
        tar -xf kernel_src/Kernel.tar.gz -C kernel_src
        mv kernel_src/kernel-5.10 linux

    - name: Clone Kali NetHunter Kernel Builder
      run: |
        git clone https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-kernel-builder.git builder

    - name: Configure local.config with LXC & uinput
      run: |
        cd builder
        cat > local.config <<EOF
        SOURCE_DIR=../linux
        KERNEL_DEFCONFIG=${DEFCONFIG}
        KERNEL_ARCH=arm64
        DEVICE_CODENAME=${DEVICE_CODENAME}
        BUILD_MODULES=1
        ANYKERNEL=1
        LXC=1
        NETHUNTER_INPUT=1
        APPLY_PATCHES=1
        EOF

    - name: Run dabao’s build.sh non-interactively
      run: |
        cd builder
        # Automate all steps: S (setup), 4 (patches), 2 (compile), 6 (AnyKernel zip)
        printf "S\n4\n2\n6\n" | bash build.sh

    - name: Upload kernel installer ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: NetHunter-Kernel-SMX115
        path: builder/output/*.zip
