name: Build NetHunter Kernel for SM-X115

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    env:
      DEVICE_CODENAME: gta9
      DEFCONFIG: gta9_defconfig
      KERNEL_SOURCES_ZIP: SM-X115_SWA_14_Opensource.zip

    steps:
    - name: Checkout project code
      uses: actions/checkout@v4

    - name: Download Kernel Source ZIP from Release
      run: |
        wget https://github.com/Anmol6002/nethunter-kernel-smx115/releases/download/SM.x115/${KERNEL_SOURCES_ZIP}
        unzip ${KERNEL_SOURCES_ZIP} -d kernel_src
        tar -xf kernel_src/Kernel.tar.gz -C kernel_src
        mv kernel_src/kernel-5.10 linux

    - name: Clone Kali NetHunter Kernel Builder
      run: git clone https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-kernel-builder.git builder

    - name: Configure local.config
      run: |
        cd builder
        cat > local.config <<EOF
        SOURCE_DIR=../linux
        KERNEL_DEFCONFIG=${DEFCONFIG}
        KERNEL_ARCH=arm64
        DEVICE_CODENAME=${DEVICE_CODENAME}
        BUILD_MODULES=1
        ANYKERNEL=1
        EOF

    - name: Setup environment & download toolchains
      run: |
        cd builder
        ./build/envsetup.sh

    - name: Apply NetHunter Kernel Patches
      run: |
        cd builder
        ./build/patch.sh

    - name: Compile Kernel from scratch
      run: |
        cd builder
        ./build/build_kernel.sh

    - name: Upload Kernel ZIP to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NetHunter-Kernel-SMX115
        path: builder/output/*.zip
